config/routes.rb
Rails.application.routes.draw do

  resources :users, :libros, :prestamos
  resources :personas

  root 'libros#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/libro.rb
class Libro < ApplicationRecord
  has_many :prestamos
  #  HAS MANY THROUGH association
  has_many :personas, through: :prestamos
  has_many_attached :fotos
end

app/models/persona.rb
class Persona < ApplicationRecord
  has_many :prestamos
  #  HAS MANY THROUGH association
  has_many :libros, through: :prestamos
end

app/models/prestamo.rb
class Prestamo < ApplicationRecord
  belongs_to :persona
  belongs_to :libro
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  def index
    @libros = Libro.all
  end

  def new

  end

  def create
    @libro = Libro.new(libro_params)

    @libro.save
    redirect_to @libros
  end

  def edit
    @libro = Libro.find(params[:id])
  end

  private
    def libro_params
      params.require(:libro).permit(:titulo, :isbn, fotos: [])
    end

end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  def index
    @personas = Persona.all
  end

  def show
    @persona = Persona.find(params[:id])
  end

  def new
  end

  def edit
    @persona = Persona.find(params[:id])
  end

  def update
    # update Persona
    Persona.save(params[:id])
  end

  def create
    @persona = Persona.new(persona_params)

    @persona.save
    redirect_to @persona
  end

  private
    def persona_params
      params.require(:persona).permit(:nombre)
    end
end

app/controllers/prestamos_controller.rb
class PrestamosController < ApplicationController

  def index
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/prestamos_helper.rb
module PrestamosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrestomeM2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/libros/edit.html.erb
<h1>Edit Libro</h1>

<%= form_with scope: :libro, method: :put, url: libro_path, local: true do |form| %>
  <p>
    <%= form.label :titulo %><br>
    <%= form.text_field :titulo %>
  </p>

  <p>
    <%= form.label :isbn %><br>
    <%= form.text_field :isbn %>
  </p>

  <p>
    <% if @libro.fotos.attached? %>
        <% @libro.fotos.each do |foto| %>
          <%= image_tag foto.variant(resize: "200x200", rotate: "90") %>
        <% end %>
      <% end %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/libros/index.html.erb
<div>
  <p><%= link_to 'Personas', controller: 'personas' %></p>
  <p><%= link_to 'Libros', controller: 'libros' %></p>
  <p><%= link_to 'Prestamos', controller: 'prestamos' %></p>
</div>

<h1>Libros index</h1>
<table>
  <tr>
    <th colspan="2">Título</th>
    <th>ISBN</th>
    <th>Fotos</th>
  </tr>

  <% @libros.each do |libro| %>
    <tr>
      <td><%= libro.titulo %></td>
      <td><%= libro.isbn %></td>
      <td><% if libro.fotos.attached? %>
            <% libro.fotos.each do |foto| %>
              <%= image_tag foto.variant(resize: "200x200", rotate: "90") %></td>
            <% end %>
          <% end %>
      <td><%= link_to 'Edit', edit_libro_path(libro) %></td>
      <td><%= link_to 'Delete', libro, method: :delete %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New libro', new_libro_path %>

app/views/libros/new.html.erb
<h1>New Libro</h1>

<%= form_with scope: :libro, url: libros_path, local: true do |form| %>
  <p>
    <%= form.label :titulo %><br>
    <%= form.text_field :titulo %>
  </p>

  <p>
    <%= form.label :isbn %><br>
    <%= form.text_field :isbn %>
  </p>

  <p>
    <%= form.label :fotos %><br>
    <%= form.file_field :fotos, multiple: :true %>
  </p>


  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', libros_path %>

app/views/libros/show.html.erb
<p>
  <strong>Titulo:</strong>
  <%= @libro.titulo %>
</p>

<%= link_to 'Back to list', libros_path %>

app/views/personas/edit.html.erb
<h1>Edit Persona</h1>

<%= form_with scope: :persona, method: :put, url: persona_path, local: true do |form| %>
  <p>
    <%= form.label :nombre %><br>
    <%= form.text_field :nombre %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/personas/index.html.erb
<div>
  <p><%= link_to 'Personas', controller: 'personas' %></p>
  <p><%= link_to 'Libros', controller: 'libros' %></p>
  <p><%= link_to 'Prestamos', controller: 'prestamos' %></p>
</div>

<h1>Hello Personas</h1>

<table>
  <tr>
    <th colspan="2">Nombre</th>
  </tr>

  <% @personas.each do |persona| %>
    <tr>
      <td><%= persona.nombre %></td>
      <td><%= link_to 'Edit', edit_persona_path(persona) %></td>
      <td><%= link_to 'Delete', persona, method: :delete %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', personas_path %>

app/views/personas/new.html.erb
<h1>New Persona</h1>

<%= form_with scope: :persona, url: personas_path, local: true do |form| %>
  <p>
    <%= form.label :nombre %><br>
    <%= form.text_field :nombre %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/personas/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @persona.nombre %>
</p>

<%= link_to 'Back to list', personas_path %>

app/views/prestamos/index.html.erb
<div>
  <p><%= link_to 'Personas', controller: 'personas' %></p>
  <p><%= link_to 'Libros', controller: 'libros' %></p>
  <p><%= link_to 'Prestamos', controller: 'prestamos' %></p>
</div>

<h1>Prestamos index</h1>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>